const TcwPayoutService = require('../tcw-payout-srv');
const PayinService = require('../payin-srv');
const dbConnector = require('../../utils/mongo-tests-cloud-data');
const { generateYearSequence } = require('./utils');

describe('Utils', () => {
  // eslint-disable-next-line no-unused-vars
  let db;
  let client;

  beforeAll(async () => {
    const connection = await dbConnector();
    db = connection.db;
    client = connection.client;
  });

  test('should generate a number sequence with lenght of 2 date years difference', () => {
    const sequence = generateYearSequence(new Date('2018-05-01'), new Date('2021-05-01'));
    expect(sequence).toHaveLength(3);
    expect(sequence).toMatchObject([1, 2, 3]);
  });

  test('should calculate TCW payout, payin, with 12 installments a year', async () => {
    if (process.env.EDITION === 'tcw') {
      const tcwPayoutService = TcwPayoutService;
      const payinService = PayinService;
      const productConfig = {
        _id: 'bbe284b1-4c25-5246-bb0f-a92900cb9466',
        premiumType: 'net',
        advance: false,
        companyAdvance: false,
        productName: 'Pensiamoci Insieme',
        productCode: 'CF_V.008.2014.PI',
        monthsOnSubscription: 1,
        subscriptionYears: 1,
        surveyTypePerson: null,
        surveyTypeCompany: null,
        adjustedAdvance: [],
        adjustedBrackets: [],
        promoter100: false,
        options: [
          {
            _id: 'ADDITIONAL-INCOME',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 0,
            retrocessionFee: 0,
          },
          {
            _id: '1-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1300,
            retrocessionFee: 7000,
          },
          {
            _id: '2-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2100,
            retrocessionFee: 7000,
          },
          {
            _id: '3-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2900,
            retrocessionFee: 7000,
          },
          {
            _id: '4-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 3700,
            retrocessionFee: 7000,
          },
          {
            _id: '5-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 4500,
            retrocessionFee: 7000,
          },
          {
            _id: '6-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 5300,
            retrocessionFee: 7000,
          },
          {
            _id: '7-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 6100,
            retrocessionFee: 7000,
          },
          {
            _id: '8-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 6900,
            retrocessionFee: 7000,
          },
          {
            _id: '9-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 7700,
            retrocessionFee: 7000,
          },
          {
            _id: '10-PLUS-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 8500,
            retrocessionFee: 7000,
          },
          {
            _id: '1-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 500,
            retrocessionFee: 7000,
          },
          {
            _id: '2-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 500,
            retrocessionFee: 7000,
          },
          {
            _id: '3-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 500,
            retrocessionFee: 7000,
          },
          {
            _id: '4-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 500,
            retrocessionFee: 7000,
          },
          {
            _id: '5-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 500,
            retrocessionFee: 7000,
          },
          {
            _id: '6-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 500,
            retrocessionFee: 7000,
          },
          {
            _id: '7-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 500,
            retrocessionFee: 7000,
          },
          {
            _id: '8-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 500,
            retrocessionFee: 7000,
          },
          {
            _id: '9-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 500,
            retrocessionFee: 7000,
          },
          {
            _id: '10-PLUS-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 500,
            retrocessionFee: 7000,
          },
        ],
      };

      const payin = payinService.calculatePayin(74256, 75256, '10-PLUS-YEARS', 1, productConfig, 0);
      const payout = tcwPayoutService.calculatePayout(74256, 75256, '10-PLUS-YEARS', 1, payin, productConfig);

      expect(payin).toBe(63118);
      expect(payout).toBe(44182);
    }
  }, 600000);

  test('should calculate TCW payout, payin, with 12 installments a year and 3 month advance', async () => {
    if (process.env.EDITION === 'tcw') {
      const tcwPayoutService = TcwPayoutService;
      const payinService = PayinService;
      const productConfig = {
        _id: 'ed347f25-de2c-874f-896a-a72000dcb789',
        premiumType: 'gross',
        advance: true,
        companyAdvance: false,
        productName: 'Risparmio & Investimento',
        productCode: 'ULPACRI',
        monthsOnSubscription: 3,
        subscriptionYears: 1,
        surveyTypePerson: null,
        surveyTypeCompany: null,
        adjustedAdvance: [],
        adjustedBrackets: [],
        promoter100: false,
        options: [
          {
            _id: 'ADDITIONAL-INCOME',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 0,
            retrocessionFee: 0,
          },
          {
            _id: '1-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 5625,
          },
          {
            _id: '2-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 800,
            retrocessionFee: 5625,
          },
          {
            _id: '3-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1200,
            retrocessionFee: 5625,
          },
          {
            _id: '4-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1600,
            retrocessionFee: 5625,
          },
          {
            _id: '5-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2000,
            retrocessionFee: 5625,
          },
          {
            _id: '6-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2400,
            retrocessionFee: 5625,
          },
          {
            _id: '7-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2800,
            retrocessionFee: 5625,
          },
          {
            _id: '8-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 3200,
            retrocessionFee: 5625,
          },
          {
            _id: '9-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 3600,
            retrocessionFee: 5625,
          },
          {
            _id: '10-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 4000,
            retrocessionFee: 5625,
          },
          {
            _id: '11-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 4400,
            retrocessionFee: 5625,
          },
          {
            _id: '12-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 4800,
            retrocessionFee: 5625,
          },
          {
            _id: '13-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 5200,
            retrocessionFee: 5625,
          },
          {
            _id: '14-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 5600,
            retrocessionFee: 5625,
          },
          {
            _id: '15-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 6000,
            retrocessionFee: 5625,
          },
          {
            _id: '16-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 6400,
            retrocessionFee: 5625,
          },
          {
            _id: '17-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 6800,
            retrocessionFee: 5625,
          },
          {
            _id: '18-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 7200,
            retrocessionFee: 5625,
          },
          {
            _id: '19-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 7600,
            retrocessionFee: 5625,
          },
          {
            _id: '20-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 8000,
            retrocessionFee: 5625,
          },
          {
            _id: '21-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 8400,
            retrocessionFee: 5625,
          },
          {
            _id: '22-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 8800,
            retrocessionFee: 5625,
          },
          {
            _id: '23-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 9200,
            retrocessionFee: 5625,
          },
          {
            _id: '24-PLUS-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 9600,
            retrocessionFee: 5625,
          },
          {
            _id: '1-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 0,
          },
          {
            _id: '2-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 0,
          },
          {
            _id: '3-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 300,
            retrocessionFee: 0,
          },
          {
            _id: '4-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 0,
          },
          {
            _id: '5-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 500,
            retrocessionFee: 0,
          },
          {
            _id: '6-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 600,
            retrocessionFee: 0,
          },
          {
            _id: '7-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 700,
            retrocessionFee: 0,
          },
          {
            _id: '8-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 800,
            retrocessionFee: 0,
          },
          {
            _id: '9-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 900,
            retrocessionFee: 0,
          },
          {
            _id: '10-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1000,
            retrocessionFee: 0,
          },
          {
            _id: '11-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1100,
            retrocessionFee: 0,
          },
          {
            _id: '12-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1200,
            retrocessionFee: 0,
          },
          {
            _id: '13-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1300,
            retrocessionFee: 0,
          },
          {
            _id: '14-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1400,
            retrocessionFee: 0,
          },
          {
            _id: '15-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1500,
            retrocessionFee: 0,
          },
          {
            _id: '16-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1600,
            retrocessionFee: 0,
          },
          {
            _id: '17-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1700,
            retrocessionFee: 0,
          },
          {
            _id: '18-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1800,
            retrocessionFee: 0,
          },
          {
            _id: '19-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1900,
            retrocessionFee: 0,
          },
          {
            _id: '20-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2000,
            retrocessionFee: 0,
          },
          {
            _id: '21-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2100,
            retrocessionFee: 0,
          },
          {
            _id: '22-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2200,
            retrocessionFee: 0,
          },
          {
            _id: '23-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2300,
            retrocessionFee: 0,
          },
          {
            _id: '24-PLUS-YEARS',
            fromYear: 2,
            toYear: 2,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2400,
            retrocessionFee: 0,
          },
          {
            _id: '1-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '2-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '3-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '4-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '5-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '6-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '7-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '8-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '9-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '10-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '11-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '12-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '13-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '14-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '15-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '16-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '17-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '18-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '19-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '20-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '21-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '22-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '23-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
          {
            _id: '24-PLUS-YEARS',
            fromYear: 3,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 100,
            retrocessionFee: 4500,
          },
        ],
      };

      const payin = payinService.calculatePayin(480000, 480000, '20-YEARS', 1, productConfig, 0);
      const payout = tcwPayoutService.calculatePayout(480000, 480000, '20-YEARS', 1, payin, productConfig);

      expect(payin).toBe(384000);
      expect(payout).toBe(216000);
    }
  }, 600000);

  test('should calculate TCW payout, payin, with unique premium', async () => {
    if (process.env.EDITION === 'tcw') {
      const tcwPayoutService = TcwPayoutService;
      const payinService = PayinService;
      const productConfig = {
        _id: '86bfb5a8-fb72-d44a-a509-a63300ed10a8',
        premiumType: 'gross',
        advance: true,
        companyAdvance: false,
        productName: 'MultiInvest Extra',
        productCode: 'M104A',
        monthsOnSubscription: 1,
        subscriptionYears: 1,
        surveyTypePerson: 'default',
        surveyTypeCompany: 'default',
        adjustedAdvance: [],
        adjustedBrackets: [],
        promoter100: false,
        options: [
          {
            _id: 'OPTION-A',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 75000000,
            fixedAmount: 0,
            percentage: 500,
            retrocessionFee: 7000,
          },
          {
            _id: 'OPTION-A',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 75000001,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 420,
            retrocessionFee: 7000,
          },
          {
            _id: 'OPTION-B',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 75000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'OPTION-B',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 75000001,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 360,
            retrocessionFee: 7000,
          },
          {
            _id: 'OPTION-C',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 75000000,
            fixedAmount: 0,
            percentage: 300,
            retrocessionFee: 7000,
          },
          {
            _id: 'OPTION-C',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 75000001,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 300,
            retrocessionFee: 7000,
          },
          {
            _id: 'MANAGEMENT-FEE',
            fromYear: 1,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 0,
            fixedAmount: 0,
            percentage: 0,
            retrocessionFee: 8000,
          },
        ],
      };

      const payin = payinService.calculatePayin(5500000, 5500000, 'OPTION-A', 1, productConfig, 0);
      const payout = tcwPayoutService.calculatePayout(5500000, 5500000, 'OPTION-A', 1, payin, productConfig);

      expect(payin).toBe(275000);
      expect(payout).toBe(192500);
    }
  }, 600000);

  test('should calculate TCW payout, payin, with quarterly premium', async () => {
    if (process.env.EDITION === 'tcw') {
      const tcwPayoutService = TcwPayoutService;
      const payinService = PayinService;
      const productConfig = {
        _id: '209ab66a-e62f-6f4c-835c-a63400b70b8f',
        premiumType: 'gross',
        advance: false,
        companyAdvance: false,
        productName: 'Progetto',
        productCode: '17_AC TCW',
        monthsOnSubscription: 6,
        subscriptionYears: 1,
        surveyTypePerson: null,
        surveyTypeCompany: null,
        adjustedAdvance: [],
        adjustedBrackets: [],
        promoter100: false,
        options: [
          {
            _id: 'ADDITIONAL-INCOME',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-1-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 330,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-1-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-2-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 660,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-2-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-3-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 990,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-3-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-4-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1320,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-4-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-5-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1650,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-5-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-6-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1980,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-6-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-7-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2310,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-7-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-8-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2640,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-8-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-9-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2970,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-9-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-10-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 3300,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-10-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-11-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 3629,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-11-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-12-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 3960,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-12-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-13-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 4290,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-13-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-14-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 4620,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-14-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-15-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 4950,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-15-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-16-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 5280,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-16-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-17-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 5610,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-17-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-18-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 5940,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-18-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-19-PLUS-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 6000,
            retrocessionFee: 7000,
          },
          {
            _id: 'FULL-PRICING-19-PLUS-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 400,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-1-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 330,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-1-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-2-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 660,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-2-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-3-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 990,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-3-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-4-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1320,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-4-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-5-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1650,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-5-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-6-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1980,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-6-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-7-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2310,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-7-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-8-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2640,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-8-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-9-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2970,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-9-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-10-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 3300,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-10-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-11-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 3629,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-11-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-12-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 3960,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-12-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-13-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 4290,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-13-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-14-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 4620,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-14-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-15-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 4950,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-15-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-16-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 5280,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-16-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-17-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 5610,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-17-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-18-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 5940,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-18-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-19-PLUS-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 6000,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-1-19-PLUS-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-1-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 170,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-1-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-2-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 340,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-2-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-3-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 509,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-3-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-4-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 680,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-4-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-5-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 850,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-5-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-6-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1019,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-6-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-7-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1190,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-7-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-8-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1360,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-8-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-9-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1530,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-9-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-10-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1700,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-10-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-11-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 1870,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-11-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-12-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2039,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-12-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-13-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2210,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-13-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-14-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2380,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-14-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-15-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2550,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-15-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-16-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2720,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-16-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-17-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 2890,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-17-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-18-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 3000,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-18-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-19-PLUS-YEARS',
            fromYear: 1,
            toYear: 1,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 3000,
            retrocessionFee: 7000,
          },
          {
            _id: 'COMMISSION-SACRIFICE-2-19-PLUS-YEARS',
            fromYear: 2,
            toYear: 99,
            fromPremiumAmount: 0,
            toPremiumAmount: 10000000000,
            fixedAmount: 0,
            percentage: 200,
            retrocessionFee: 7000,
          },
        ],
      };

      const payin = payinService.calculatePayin(600000, 600000, 'FULL-PRICING-5-YEARS', 1, productConfig, 0);
      const payout = tcwPayoutService.calculatePayout(600000, 600000, 'FULL-PRICING-5-YEARS', 1, payin, productConfig);

      expect(payin).toBe(99000);
      expect(payout).toBe(69300);
    }
  }, 600000);

  afterAll(() => {
    client.close();
  });
});
