const ProductConfiguration = require("../product-configuration");
const Option = require("../option");

const seed = [
  {
    _id: '467c9b20-8e4d-a343-8c74-32795633fc51',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IUP15PF',
    productName: 'Uniqa Tutela Premium',
  },
  {
    _id: '33163cc2-37e7-de48-bdf8-a55300ce6441',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '515',
    productName: 'Helvetia TCM Nuova Omnia Decrescente PU - Tar. 515 Non Fumatore',
  },
  {
    _id: 'e89de2ef-921e-2a42-84df-198b7a4705df',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'ULPIP',
    productName: 'Uniqa PIP Domani Sicuro Plus',
  },
  {
    _id: 'b9c8587b-915e-274b-86c6-a60800f14440',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'MutV_01',
    productName: 'MetLife Mutuo Vivo',
  },
  {
    _id: '04e626a8-e419-f345-9dbf-a56400e4c521',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '495',
    productName: 'Helvetia Tuo Futuro Ob. Maturità - Tar. 495',
  },
  {
    _id: '4e7e8931-7b55-6e41-b073-321e122dd3ea',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'PrJr_01',
    productName: 'MetLife Protezione Junior',
  },
  {
    _id: '6cb3018a-30ee-044f-840a-a48a00caab48',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '506',
    productName: 'Helvetia Tcm Nuova Omnia - Tar. 506 Fumatore',
  },
  {
    _id: '0b68d653-a965-034e-bdee-a52f00ab1ae5',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'PLAT',
    productName: 'Mutua Tre Esse Platinum',
  },
  {
    _id: 'd7e22516-e851-a940-9537-e2a80f2f258f',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IUP34RC_05',
    productName: 'Uniqa Certezza Rendita Plus Cap. Costante',
  },
  {
    _id: '3802d0b3-1765-6442-9a28-a48e00bc1a5a',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '461',
    productName: 'Helvetia Smart 4 You',
  },
  {
    _id: 'dd4bd13a-498d-4d47-bb37-a4cc0107f05d',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '0250',
    productName: 'Eurovita Forza15 Coupon',
  },
  {
    _id: '736bb113-1edc-d747-ab98-a48800f6d801',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'US17S',
    productName: 'Darta Premium Plus',
  },
  {
    _id: '56922c7c-fbfb-c649-a1b7-8c00a60fb37a',
    advance: true,
    companyadvance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 6,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'US16S_v02K',
    productName: 'Darta Easy Multiline PU & PAC KEY MAN',
  },
  {
    _id: 'e63e23f7-fc9c-4c4b-8c4c-a4ab00602af0',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '342',
    productName: 'Helvetia InProspettiva - Tar. 342',
  },
  {
    _id: 'a866642d-ee97-5e46-bd54-506e602f797c',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'ICAP5FX_05',
    productName: 'Uniqa Capital 5 con Bonus',
  },
  {
    _id: '87844024-972a-6b42-974c-f1b324da4189',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'C54R',
    productName: 'Uniqa Key Man Protezione d’Impresa',
  },
  {
    _id: '73fd0868-2481-ee46-bcb7-a48a0128bb87',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '0.75',
    productName: 'Helvetia CERTAmenTE',
  },
  {
    _id: '522ca912-dd44-194a-87ff-809a91039445',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'Z042-Z044',
    productName: 'zInvest - PU Z042 - Z044',
  },
  {
    _id: '3b3d6559-6ddf-c94d-8648-a4cc01020525',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '9017',
    productName: 'Eurovita 50&50',
  },
  {
    _id: 'de835935-6708-5b47-a5c0-a56400f583e1',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '496',
    productName: 'Helvetia Tuo Futuro Ob. Laurea - Tar. 496',
  },
  {
    _id: '93a8a303-9223-7e49-b997-42bf9a8fb841',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'FA100COASSEA',
    productName: 'EuropAss Eura Casa Premium',
  },
  {
    _id: 'eeffdcab-e2c5-6e44-8744-a37025659a1c',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'FA100COEARCFRCC',
    productName: 'EuropAss Eura Casa Extra',
  },
  {
    _id: '2ccec3e3-2a47-7c48-82eb-ceecba62c3f7',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'C11B',
    productName: 'Italiana PIP Feelgood',
  },
  {
    _id: '2b63a83e-01f9-274e-afed-239fc7190f29',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '0296',
    productName: 'Eurovita SMART - Cedola Semestrale',
  },
  {
    _id: '802632ef-bc1f-dd4c-8e13-d333892c03ed',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'FA100COEARCFRCCZ1',
    productName: 'EuropAss Eura Casa Extra – Zona 1',
  },
  {
    _id: '0cc7e5d4-c0ba-f24f-8079-7cd00f9d678d',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'FA100COASSESAZ2',
    productName: 'EuropAss Eura Casa Premium – Zona 2',
  },
  {
    _id: 'c390439f-f909-294c-b4fa-a91a00ddba3a',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'VIAGGI',
    productName: 'EuropAss Viaggi NoStop Vacanza',
  },
  {
    _id: '209ab66a-e62f-6f4c-835c-a63400b70b8f',
    productName: 'Progetto',
    productCode: '17_AC',
    monthsOnSubscription: 6,
    advance: true,
    companyAdvance: false,
    subscriptionYears: 1,
    options: [
      {
        _id: 'ADDITIONAL-INCOME',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-1-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 330,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-1-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-2-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 660,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-2-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-3-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 990,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-3-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-4-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 1320,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-4-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-5-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 1650,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-5-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-6-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 1980,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-6-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-7-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 2310,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-7-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-8-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 2640,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-8-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-9-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 2970,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-9-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-10-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 3300,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-10-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-11-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 3630,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-11-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-12-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 3960,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-12-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-13-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 4290,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-13-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-14-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 4620,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-14-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-15-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 4950,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-15-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-16-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 5280,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-16-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-17-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 5610,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-17-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-18-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 5940,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-18-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-19-PLUS-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 6000,
        retrocessionFee: 8000,
      },
      {
        _id: 'FULL-PRICING-19-PLUS-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 400,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-1-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 330,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-1-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-2-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 660,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-2-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-3-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 990,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-3-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-4-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 1320,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-4-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-5-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 1650,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-5-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-6-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 1980,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-6-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-7-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 2310,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-7-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-8-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 2640,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-8-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-9-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 2970,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-9-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-10-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 3300,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-10-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-11-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 3630,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-11-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-12-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 3960,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-12-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-13-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 4290,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-13-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-14-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 4620,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-14-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-15-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 4950,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-15-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-16-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 5280,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-16-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-17-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 5610,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-17-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-18-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 5940,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-18-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-19-PLUS-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 6000,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-1-19-PLUS-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-1-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 170,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-1-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-2-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 340,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-2-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-3-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 510,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-3-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-4-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 680,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-4-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-5-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 850,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-5-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-6-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 1020,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-6-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-7-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 1190,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-7-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-8-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 1360,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-8-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-9-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 1530,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-9-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-10-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 1700,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-10-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-11-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 1870,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-11-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-12-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 2040,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-12-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-13-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 2210,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-13-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-14-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 2380,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-14-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-15-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 2550,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-15-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-16-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 2720,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-16-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-17-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 2890,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-17-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-18-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 3000,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-18-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-19-PLUS-YEARS',
        fromYear: 1,
        toYear: 1,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 3000,
        retrocessionFee: 8000,
      },
      {
        _id: 'COMMISSION-SACRIFICE-2-19-PLUS-YEARS',
        fromYear: 2,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 200,
        retrocessionFee: 8000,
      },
    ],
    premiumType: 'gross',
  },
  {
    _id: 'd57e5303-931f-b948-9f0e-a5af011ff7d9',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '981A',
    productName: 'zIntegra - Premio Unico',
  },
  {
    _id: '3f6fd09a-776d-9b43-865f-a6cd00fb4fc1',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'SA',
    productName: "Italiana STUDIO & ATTIVITA'",
  },
  {
    _id: 'd30b55e4-7197-ca49-993b-5c75338dd490',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'FA100COASSESAZ3',
    productName: 'EuropAss Eura Casa Premium – Zona 3',
  },
  {
    _id: 'ec448cee-10f3-9c42-9e38-5857c1e63de5',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '0371',
    productName: 'Eurovita SuperPir - Custom',
  },
  {
    _id: '9f34accd-659c-b846-b9f1-a96900c079c7',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'TANDEM',
    productName: 'Italiana TANDEM',
  },
  {
    _id: 'b6a91a11-7a4c-0344-96b9-b514c9045094',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'NewPr_01',
    productName: 'MetLife New Protecition',
  },
  {
    _id: 'c20535d7-f670-594f-9494-a55300bc719f',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '512',
    productName: 'Helvetia TCM Nuova Omnia Decrescente- Tar. 512 Fumatore',
  },
  {
    _id: 'b02ecf39-9b00-0041-b68e-85af023901c3',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'PrMente_01',
    productName: 'MetLife Pronta Mente',
  },
  {
    _id: '2cbf2728-a79c-5140-883b-a6cd00c5cd32',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'MAL50004',
    productName: 'Italiana FIRST PROTECTION FAMILY',
  },
  {
    _id: '05484554-53b9-544f-8f93-dcddd72b9386',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '0294',
    productName: 'Eurovita SMART - Capitalizzazione Interessi',
  },
  {
    _id: '8dede24d-7ecb-404b-aa02-9d9124b72ded',
    advance: true,
    companyadvance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IM9013_50',
    productName: 'Eurovita Obiettivo Risparmio - 50&50',
  },
  {
    _id: '1f8de10c-6086-314e-ab31-c1e35cb19c41',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'SalCompl_4Stelle',
    productName: 'RBM Salute Completa 4 Stelle',
  },
  {
    _id: 'dc7925c5-5e9e-7546-9650-a7c100e9460e',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'RcAss',
    productName: 'Assigeco RC',
  },
  {
    _id: 'a64ab8ef-a543-5448-844d-a5bf011a3bc1',
    advance: true,
    companyadvance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 6,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'US16S_v02',
    productName: 'Darta Easy Multiline PU & PAC',
  },
  {
    _id: '8f258181-2861-7343-b496-f9c54ab2c4a3',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IUP22RX_05',
    productName: 'Uniqa Futuro & Sicurezza Extra',
  },
  {
    _id: '8b58d85f-a31c-6041-810f-51e1c1013385',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'Lib_01',
    productName: 'MetLife Liberamente Più',
  },
  {
    _id: '20470d69-a917-c442-a992-a5280004b55f',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'Silv',
    productName: 'Mutua Tre Esse  - Silver',
  },
  {
    _id: '2f0723ad-4ee7-d94e-bebb-a48d0058ac57',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '221',
    productName: 'Helvetia Crea 1.5 - Risparmio',
  },
  {
    _id: 'cd559770-c9a7-0940-b7dc-a5b50119940d',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IGB',
    productName: 'zPlatform evolution',
  },
  {
    _id: 'c5f3c399-06bc-7041-a893-a63400bdb00f',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '275',
    productName: 'Helvetia Multiattiva - Versione Accumulo',
  },
  {
    _id: '3b213fea-78a0-7343-a116-9c8fd3956c08',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'RC500ASS',
    productName: 'EuropAss Eura Famiglia Light',
  },
  {
    _id: '4b2cfb54-d734-fa40-891f-98fe14e9bf77',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'Z045',
    productName: 'Zurich Target Solution - Premio Unico',
  },
  {
    _id: 'e674e639-edd3-c045-9307-8778cc6b2be6',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'FA70ASSEA',
    productName: 'EuropAss Eura Casa Light',
  },
  {
    _id: 'f502c1d9-0246-6946-b0c9-0de0ca9d3a9a',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '0295',
    productName: 'Eurovita SMART - Cedola Annuale',
  },
  {
    _id: 'fe8a72e6-98f3-064e-8d14-17bbbc6e5e38',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'ARCA001',
    productName: 'Arca Previdenza - PIP',
  },
  {
    _id: '1b41fa88-e88c-9f45-9195-a90c00794105',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'TLImpr',
    productName: 'ARAG - Tutela Legale Impresa',
  },
  {
    _id: '86bfb5a8-fb72-d44a-a509-a63300ed10a8',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'MultInv',
    productName: 'Zurich MultInvest Extra',
  },
  {
    _id: '1032895e-4dff-6145-bf8f-423b50288251',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IUP490T_00',
    productName: 'Uniqa Contopolizza Dinamico',
  },
  {
    _id: '87373385-f189-3c44-896d-a4ab00651918',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '345',
    productName: 'Helvetia InProspettiva - Tar. 345',
  },
  {
    _id: '9784b40e-a538-b244-8d18-a52f00a9e5f0',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'Gold',
    productName: 'Mutua Tre Esse Gold',
  },
  {
    _id: '36674b38-d3ab-5943-9df2-4c0f3bb0ffc8',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IUP54R',
    productName: 'Uniqa Titutela Premio Annuo',
  },
  {
    _id: '16cfed28-89db-7e48-b7c3-51c77d22555e',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'FA100COASESARCFRCCZ3',
    productName: 'EuropAss Eura Casa Extra – Zona 3',
  },
  {
    _id: '8df0b8b1-da97-f04d-8543-a66df923c603',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'Amiss',
    productName: 'B&C Amissima',
  },
  {
    _id: '29d69caa-66bf-a945-bfa7-a5e500e43c67',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IUP494',
    productName: 'Uniqa Contopolizza Cash',
  },
  {
    _id: 'ce7474c4-6d87-2243-9095-a5af012408bc',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'Z041-Z043',
    productName: 'zInvest - PU Z041 - Z043',
  },
  {
    _id: 'ee0fe395-4a41-e54d-adea-0f1b4c67271b',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'RC500ASSRCLINFM',
    productName: 'EuropAss Eura Famiglia Extra',
  },
  {
    _id: '582ba9a0-4e67-ca40-8ca4-a6cd00f720ad',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'MULTI53140',
    productName: 'Italiana ARTIGIANO',
  },
  {
    _id: 'f6e4ac59-5bf5-6140-a2c4-a98a00e6009c',
    advance: true,
    companyadvance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'Lib_02.02',
    productName: 'MetLife Liberamente Più 2018.2',
  },
  {
    _id: '2b221231-eb90-9849-9aa9-a52c00fa4a89',
    advance: true,
    companyadvance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 6,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'US16S_KeyM',
    productName: 'Darta Easy ML Key Men',
  },
  {
    _id: '5a349c35-1333-a64c-81b1-a51b00d0f059',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'PUL2S',
    productName: 'Darta Saving Life Protection',
  },
  {
    _id: '977aec7b-576c-2b42-bb97-a67c00a75d2f',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'RC500ASSRCL',
    productName: 'EuropAss Eura Famiglia Premium',
  },
  {
    _id: '7e445616-151e-814a-98b2-82a5da742d17',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '428A',
    productName: 'Italiana GHIBLI',
  },
  {
    _id: '1a3064f3-c9ac-a94e-93c9-a65413305e50',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'Z046',
    productName: 'Zurich Target Solution - Premio Unico con Caricamento',
  },
  {
    _id: '8c81e3c0-c7db-184b-8b51-a46d0166b8ea',
    advance: true,
    companyadvance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 6,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'US16S',
    productName: 'Darta Easy Multiline',
  },
  {
    _id: '7eb3397a-e88f-5a41-a26a-33d4e21f7112',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '0297',
    productName: 'Eurovita SMART - Cedola Mensile',
  },
  {
    _id: '97074dd0-6bb2-a849-bdfc-527ff13ee8f9',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IUP490PT',
    productName: 'Uniqa Contopolizza Protetto',
  },
  {
    _id: 'c95e1a90-e4c2-9f47-9d9b-a6240093f18f',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '01_Vicev',
    productName: 'AssiOne - TCM Viceversa',
  },
  {
    _id: '0bba0817-cd9e-a94f-9cf1-a48a010f00f7',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '508',
    productName: 'Helvetia Tcm Nuova Omnia - Tar. 508 Fumatore',
  },
  {
    _id: '714fac83-2971-1440-99d3-a5af011af6a5',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '98A',
    productName: 'zIntegra - Premio Annuo',
  },
  {
    _id: 'a6542098-be3a-8b49-854d-a4cc010618e2',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '0249',
    productName: 'Eurovita Forza 15',
  },
  {
    _id: 'ee3a32d3-d88b-ea4d-9101-a55300bf7be1',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '513',
    productName: 'Helvetia TCM Nuova Omnia Decrescente- Tar. 513 Non Fumatore',
  },
  {
    _id: '98ce8702-8a5d-c745-8575-7bbe99620958',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'PREMIUM',
    productName: 'EuropAss Eura Salute Premium',
  },
  {
    _id: '84c17524-47a2-9f48-ac1c-f32e9d65f075',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IUP34RC_05_v02',
    productName: 'Uniqa Certezza Rendita Più',
  },
  {
    _id: '2b2d5287-0ff1-d64d-b7d3-1e0c8c57a178',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'TutSalute_2.0',
    productName: 'RBM Tutta Salute 2.0',
  },
  {
    _id: '170efda8-1578-6f41-96cf-a48f00f243eb',
    advance: true,
    companyadvance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '264',
    productName: 'Helvetia Aequa - PIP',
  },
  {
    _id: '588fa19d-05ed-214c-a493-a55300ccf685',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '514',
    productName: 'Helvetia TCM Nuova Omnia Decrescente PU - Tar. 514 Fumatore',
  },
  {
    _id: '8c645ff5-c321-9444-bdd0-a48d00504c12',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '219',
    productName: 'Helvetia Crea 1.5 - Consolida',
  },
  {
    _id: 'b528c8da-ac26-c04e-81e0-a4cc01042d12',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '9016',
    productName: 'EUROVITA QUALITY',
  },
  {
    _id: 'ed347f25-de2c-874f-896a-a72000dcb789',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'ULPACRI',
    productName: 'Uniqa Risparmio & Investimento',
  },
  {
    _id: '5813c566-ecd9-864b-80b5-e46729121150',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'FA100COASSEAZ1',
    productName: 'EuropAss Eura Casa Premium – Zona 1',
  },
  {
    _id: 'a368d4f2-4e45-8b45-b5b6-b0e401e7bcb4',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'SalCompl_1Stella',
    productName: 'RBM Salute Completa 1 Stella',
  },
  {
    _id: '671f8661-76e1-a84e-88b8-c57aa9c2a5f3',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'SalCompl_5Stelle',
    productName: 'RBM Salute Completa 5 Stelle',
  },
  {
    _id: 'eaf5cc36-70c3-b543-963b-a63400d1b18c',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '272',
    productName: 'Helvetia Multiattiva - Versione Pr. Unico',
  },
  {
    _id: '6dd39b24-a1d9-c542-b116-835d67412b78',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '0288',
    productName: 'Eurovita Forza 15 Premium',
  },
  {
    _id: '22e4e424-3d8b-7a49-b27a-6d0c639e472e',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'LIGHT',
    productName: 'EuropAss Eura Salute Light',
  },
  {
    _id: '3d908a0a-bbe9-5c46-a296-6232d989ce80',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'A04A',
    productName: 'Italiana PU MATCH',
  },
  {
    _id: 'b1161889-c002-7642-a7e6-ccdf93b16feb',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'SalCompl_3Stelle',
    productName: 'RBM Salute Completa 3 Stelle',
  },
  {
    _id: 'dd00b85e-262a-8b4b-a5d8-a90b00f5db4c',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'TLVita',
    productName: 'ARAG - Tutela Legale per la Vita',
  },
  {
    _id: 'af64bd17-184a-4044-a16d-fc204fa7829f',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IUP67R_05',
    productName: 'Uniqa Young Doppio Bonus',
  },
  {
    _id: '1060a078-231c-9349-8b7c-a48a0114f231',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '511',
    productName: 'Helvetia Tcm Nuova Omnia - Tar. 511 Non Fumatore - Selez Medica',
  },
  {
    _id: '2e266806-3be9-004a-b1db-a4ab0063b747',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '344',
    productName: 'Helvetia InProspettiva - Tar. 344',
  },
  {
    _id: '392fff6b-750b-b64b-a8ff-a4880100b854',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'US12S',
    productName: 'Darta Premium Plus Multiline',
  },
  {
    _id: '525c1553-d1f6-2f43-93d6-a48d005ce232',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '223',
    productName: 'Helvetia Crea 1.5 - Premium',
  },
  {
    _id: 'c3374374-5497-ac41-b97e-a4ab00627ccd',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '343',
    productName: 'Helvetia InProspettiva - Tar. 343',
  },
  {
    _id: 'f5127563-8d7a-3b49-9ebb-a4cc010ade95',
    advance: true,
    companyadvance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 6,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'PUL1S',
    productName: 'Darta Long Term Care',
  },
  {
    _id: '2ad3b577-61b6-ff49-a89a-7d11e02b40db',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IUP16CU',
    productName: 'Uniqa Tutela Senzatempo',
  },
  {
    _id: '0e998bb2-318e-c741-849b-f9a33c1e4d56',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'EXTRA',
    productName: 'EuropAss Eura Salute Extra',
  },
  {
    _id: '29807dba-fcd7-694c-89cf-a6c90106cd89',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'A03A',
    productName: 'Italiana Tetris PU Ed. Limitata PU',
  },
  {
    _id: 'c973bdbe-3f52-8949-92ef-0abcfe9b1c2e',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'FA70ASSESAZ1&2',
    productName: 'EuropAss Eura Casa Light – Zona 1&2',
  },
  {
    _id: 'bbba8315-0a76-b84c-8928-d88d5ed4a254',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'SalCompl_2Stelle',
    productName: 'RBM Salute Completa 2 Stelle',
  },
  {
    _id: 'bb55b51a-5868-664d-b6fb-655dadc02748',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'AmTrust',
    productName: 'B&C AM Trust International',
  },
  {
    _id: 'cc832458-eb5c-724a-a88f-fc4db81c0d99',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'Ass1Rc',
    productName: 'Assi One',
  },
  {
    _id: 'f66c91e5-0d58-954f-bb6c-a5ee01157742',
    advance: true,
    companyadvance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IT5614',
    productName: 'Eurovita Valore Eurotandem',
  },
  {
    _id: 'fdc8286c-08d9-a441-a8d7-a48d00566a27',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '220',
    productName: 'Helvetia Crea 1.5 - Cedola',
  },
  {
    _id: 'd01dd7fa-3a44-2f4b-bf3c-a48a0105ce52',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '507',
    productName: 'Helvetia Tcm Nuova Omnia - Tar. 507 Non Fumatore',
  },
  {
    _id: '06b87e79-adbe-8c48-8d1b-54684561c445',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'FA100COASESARCFRCCZ2',
    productName: 'EuropAss Eura Casa Extra – Zona 2',
  },
  {
    _id: 'aa03882a-8936-234b-908f-2b69582198ab',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'ElitIns',
    productName: 'B&C Elite Insurance',
  },
  {
    _id: 'd354e826-7469-c440-81db-4c636e53f7d6',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'C460_00',
    productName: 'Uniqa Contopolizza Risparmio',
  },
  {
    _id: '0b5cd248-d0ec-834c-aa5b-a6c90107cada',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '400A',
    productName: 'Italiana Lifemotiv a Premio Unico',
  },
  {
    _id: '2e400e3a-6af7-6646-8c54-a6cd00f9614a',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'MULTI57134',
    productName: 'Italiana COMMERCIANTE',
  },
  {
    _id: 'a3d44552-6654-4548-9a4f-168d5ecd522e',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'FA70ASSESAZ3',
    productName: 'EuropAss Eura Casa Light – Zona 3',
  },
  {
    _id: 'cc500937-3c47-1342-985d-a48a011268c4',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: '509',
    productName: 'Helvetia Tcm Nuova Omnia - Tar. 509 Non Fumatore',
  },
  {
    _id: '35df9431-fa95-0449-9a49-936805924093',
    advance: false,
    companyadvance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'IM9013_80',
    productName: 'Eurovita Obiettivo Risparmio - 20&80',
  },
  {
    _id: '0b4faeda-3468-de47-8f35-a969009b9c19',
    advance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'US07S',
    productName: 'Darta Periodical Solution',
  },
  {
    _id: '174ffb2e-72d4-7047-bbfd-a98500cfa6cf',
    advance: true,
    companyadvance: false,
    companyAdvance: false,
    subscriptionYears: 1,
    monthsOnSubscription: 1,
    options: [
      {
        _id: 'DEFAULT',
        fromYear: 1,
        toYear: 99,
        fromPremiumAmount: 0,
        toPremiumAmount: 10000000000,
        fixedAmount: 0,
        percentage: 0,
        retrocessionFee: 0,
      },
    ],
    premiumType: 'gross',
    productCode: 'Lib_02.01',
    productName: 'MetLife Liberamente Più 2018',
  },
].map((conf) => new ProductConfiguration({ ...conf, options: conf.options.map((opt) => new Option(opt)) }));

module.exports = { seed };
