version: "3.3"
services:
  naspi_web:
    image: yiisoftware/yii2-php:7.2-apache
    container_name: naspi_web
    ports:
      - "80:80"
    volumes:
      - ./web:/app
    environment:
    - PHP_ENABLE_XDEBUG=1
  naspi_mysql:
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: database
    container_name: naspi_mysql
    restart: 'no'
  liquibase:
    image: liquibase/liquibase
    depends_on:
      - naspi_mysql
    environment:
      PMA_HOST: naspi_mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: database
    restart: always
    ports:
      - 8081:80
  liquibase:
    image: liquibase/liquibase
    depends_on:
      - naspi_mysql
    volumes:
      - ./liquibase:/liquibase/changelog/
    command: --defaults-file=/liquibase/changelog/liquibase.properties update