branch-defaults:
  FEAT-setup-build:
    environment: tcw-api-dev
global:
  application_name: Prassi API
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
