function translateEntryOrigin(origin) {
  const origins = {
    'advance+indirect': 'Anticipo provvigioni indirette',
    'advance+indirect-2021': 'Anticipo provvigioni indirette',
    'cash-in+indirect': 'Provvigioni di incasso indirette',
    'cash-in+indirect-2021': 'Provvigioni di incasso indirette',
    'purchase+indirect': 'Provvigioni di acquisto indirette',
    'purchase+indirect-2021': 'Provvigioni di acquisto indirette',
    'advance+direct': 'Anticipo provvigioni dirette',
    'advance+direct-2021': 'Anticipo provvigioni dirette',
    'cash-in+direct': 'Provvigioni di incasso dirette',
    'cash-in+direct-2021': 'Provvigioni di incasso dirette',
    'purchase+direct': 'Provvigioni di acquisto dirette',
    'purchase+direct-2021': 'Provvigioni di acquisto dirette',
    'basis+': 'Provvigioni di base',
    'range+': 'Provvigioni di fascia',
    'target+': 'Provvigioni di target',
    'management-fee': 'Management fee',
    'gmv-guaranteed+monthly': 'Garantito mensile variabile',
    'gmv-guaranteed-variable': 'Garantito minimo variabile',
    'guaranteed+monthly': 'Garantito mensile',
    'guaranteed-variable': 'Garantito variabile',
    'guaranteed+one-time': 'Garantito',
    'conditioned+rappel+payment-delayed': 'Rappel',
    'conditioned+rappel-3+payment-delayed': 'Rappel a 3 fasce',
    'conditioned+welcome-bonus+prepayment': 'Welcome Bonus',
    'conditioned+welcome-bonus+recovery': 'Recupero Welcome Bonus',
    'conditioned+guaranteed-with-bonus+payment-delayed': 'Bonus Garantito',
    'conditioned+guaranteed-with-bonus-prepaid+prepayment': 'Bonus Anticipato Garantito',
    'conditioned+guaranteed-with-bonus-prepaid+recovery': 'Recupero Bonus Anticipato Garantito',
    'write-off-commission-purchase': 'Storno provvigioni',
    'write-off-commission-damage': 'Storno provvigioni danni',
    'write-off-commission-mf': 'Storno provvigioni MFee',
    'write-off-rappel': 'Storno rappel',
    'write-off-production-prize': 'Storno premio produzione',
    'write-off-rectruiting-prize': 'Storno premio recruiting',
    'write-off-guaranteed-bonus': 'Storno bonus garantito',
    'future-direct+direct': 'Anticipazione in conto provvigioni future (dirette)',
    'future-direct+indirect': 'Anticipazione in conto provvigioni future (indirette)',
    'write-off+direct': 'Recupero anticipazione in conto provvigioni future (dirette)',
    'write-off+indirect': 'Recupero anticipazione in conto provvigioni future (indirette)',
    'recruiting-prize': 'Premio di recruiting',
    'production-prize': 'Premio produzione',
    'replacement-commission': 'Commissioni segnalazione',
    starling: 'Storno',
    balance: 'Conguaglio Sovraprovvigioni',
    advance: 'Anticipo spettanze',
    debit: 'Recupero anticipo',
    other: 'Altro',
    stamp: 'Imposta di bollo',
    'taxable-withholding': 'Imponibile ritenuta d’acconto (50% dei corrispettivi lordi)',
    withholding: 'Ritenuta d’acconto 11,5% sul compenso',
    'withholding-20': 'Ritenuta d’acconto 20% sul compenso',
    'withholding-46': 'Ritenuta d’acconto 4,6% sul compenso',
    'commissioning-value': 'Provvigioni',
    'commissioning-damage': 'Provvigioni Danni',
    'commissioning-cashin': 'Provvigioni Incasso',
    'commissioning-mfee': 'Provvigioni MFee',
    'rappel-quarter': 'Rappel trimestrale',
    'rappel-semester': 'Rappel semestrale',
    'rappel-yearly': 'Rappel annuale',
    'bonus-guaranteed': 'Bonus garantito',
    'write-off-balance': 'Storno Conguaglio Sovraprovvigioni',
  };
  return origins[`${origin}`] || origin;
}

module.exports = translateEntryOrigin;
