const seed = [
  {
    authenticationId: 1000,
    authenticationName: 'Sistema',
    name: 'Sistema',
    networkId: 'system',
    color: 'headquarter',
    shortName: 'SY',
    area: 'none',
  },
  {
    authenticationId: 7,
    authenticationName: 'Direzione',
    name: 'Direzione',
    networkId: 'administrator',
    color: 'headquarter',
    shortName: 'DIR',
    area: 'direzione',
  },
  {
    authenticationId: 6,
    authenticationName: 'Responsabile Reti',
    name: 'Responsabile Reti',
    networkId: 'district-manager',
    color: 'district',
    shortName: 'RR',
    area: 'area',
  },
  {
    authenticationId: 5,
    authenticationName: 'Area Manager',
    name: 'Area Manager Junior',
    networkId: 'branch-manager-junior',
    color: 'branch',
    shortName: 'AM',
    area: 'filiale',
  },
  {
    authenticationId: 5,
    authenticationName: 'Area Manager',
    name: 'Area Manager',
    networkId: 'branch-manager',
    color: 'branch',
    shortName: 'AM',
    area: 'filiale',
  },
  {
    authenticationId: 2,
    authenticationName: 'Promotore',
    name: 'Promotore Senior',
    networkId: 'promoter-senior',
    color: 'promoter',
    shortName: 'PS',
    area: 'zona',
  },
  {
    authenticationId: 3,
    authenticationName: 'Team Manager',
    name: 'Team Manager Junior',
    networkId: 'team-manager-junior',
    color: 'team',
    shortName: 'TMJ',
    area: 'settore',
  },
  {
    authenticationId: 3,
    authenticationName: 'Team Manager',
    name: 'Team Manager',
    networkId: 'team-manager',
    color: 'team',
    shortName: 'TM',
    area: 'settore',
  },
  {
    authenticationId: 2,
    authenticationName: 'Promotore',
    name: 'Consulente Previdenziale',
    networkId: 'promoter',
    color: 'promoter',
    shortName: 'CP',
    area: 'zona',
  },
  {
    authenticationId: 1,
    authenticationName: 'Guest',
    name: 'Segnalatore',
    networkId: 'signaller',
    color: 'signaller',
    shortName: 'SE',
    area: 'segnalatore',
  },
];

module.exports = { seed };
